package Entidades;
// Generated 14-jul-2016 15:51:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String categoria;
     private String tipo;
     private String titulo;
     private String descripcion;
     private long precio;
     private String moneda;
     private String whatsap;
     private Date publicado;
     private String foto1;
     private String foto2;
     private String foto3;
     private String foto4;
     private String foto5;

    public Anuncio() {
    }

	
    public Anuncio(Usuario usuario, String categoria, String tipo, String titulo, String descripcion, long precio, String moneda, String whatsap, Date publicado) {
        this.usuario = usuario;
        this.categoria = categoria;
        this.tipo = tipo;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.precio = precio;
        this.moneda = moneda;
        this.whatsap = whatsap;
        this.publicado = publicado;
    }
    public Anuncio(Usuario usuario, String categoria, String tipo, String titulo, String descripcion, long precio, String moneda, String whatsap, Date publicado, String foto1, String foto2, String foto3, String foto4, String foto5) {
       this.usuario = usuario;
       this.categoria = categoria;
       this.tipo = tipo;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.moneda = moneda;
       this.whatsap = whatsap;
       this.publicado = publicado;
       this.foto1 = foto1;
       this.foto2 = foto2;
       this.foto3 = foto3;
       this.foto4 = foto4;
       this.foto5 = foto5;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(long precio) {
        this.precio = precio;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getWhatsap() {
        return this.whatsap;
    }
    
    public void setWhatsap(String whatsap) {
        this.whatsap = whatsap;
    }
    public Date getPublicado() {
        return this.publicado;
    }
    
    public void setPublicado(Date publicado) {
        this.publicado = publicado;
    }
    public String getFoto1() {
        return this.foto1;
    }
    
    public void setFoto1(String foto1) {
        this.foto1 = foto1;
    }
    public String getFoto2() {
        return this.foto2;
    }
    
    public void setFoto2(String foto2) {
        this.foto2 = foto2;
    }
    public String getFoto3() {
        return this.foto3;
    }
    
    public void setFoto3(String foto3) {
        this.foto3 = foto3;
    }
    public String getFoto4() {
        return this.foto4;
    }
    
    public void setFoto4(String foto4) {
        this.foto4 = foto4;
    }
    public String getFoto5() {
        return this.foto5;
    }
    
    public void setFoto5(String foto5) {
        this.foto5 = foto5;
    }




}


