package Entidades;
// Generated 14-jul-2016 15:51:28 by Hibernate Tools 4.3.1



/**
 * Tipocategoria generated by hbm2java
 */
public class Tipocategoria  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private String tipoCategoria;

    public Tipocategoria() {
    }

    public Tipocategoria(Categoria categoria, String tipoCategoria) {
       this.categoria = categoria;
       this.tipoCategoria = tipoCategoria;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getTipoCategoria() {
        return this.tipoCategoria;
    }
    
    public void setTipoCategoria(String tipoCategoria) {
        this.tipoCategoria = tipoCategoria;
    }




}


