package Entidades;
// Generated 14-jul-2016 15:51:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private String sexo;
     private int edad;
     private String telefono;
     private String email;
     private String clave;
     private Set anuncios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String apellidos, String sexo, int edad, String telefono, String email, String clave) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.sexo = sexo;
        this.edad = edad;
        this.telefono = telefono;
        this.email = email;
        this.clave = clave;
    }
    public Usuario(String nombre, String apellidos, String sexo, int edad, String telefono, String email, String clave, Set anuncios) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.edad = edad;
       this.telefono = telefono;
       this.email = email;
       this.clave = clave;
       this.anuncios = anuncios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


